### ISSUE TITLE
Permission denied: b'/.ansible'

### ISSUE THREAD

**Issue by brenzi** [flex-dapps/gantree-cli#13]
I'm retrying to deploy my node (which is based on a fresh node-template
 2.0.0-alpha.5)

my config
```
{
    "metadata":{
        "version":"2.0",
        "project":"nctr-test"
    },
    "binary":{
        "chain":false,
        "fetch":{
            "url":"https://github.com/encointer/encointer-node/releases/download/v0.2.0/encointer-node",
            "sha256":"0c0cda03410bff227c693a140094e2c8da6d9192238f5fe4e190ce7fab962af1"
        },
        "filename":"encointer-node",
        "useBinChainSpec":"true"
    },
    "nodes":[
        {
            "validator":false,
            "instance":{
                "sshPrivateKeyPath": "/gantree/ssh/ssh_id_rsa_validator",
                "provider":"do",
                "dropletSize":"s-2vcpu-4gb",
                "region":"fra1",
                "sshPublicKey": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDg4KTwEVbIG5FjmfX0E/Ip0HPOiOKKPAc+8yS4KO1fIJMMdHBybnRVrMHZL22DmQnih/Q1O6Zw4SPV5Ou+mZ4Ojz4JKv3VQ8HdIp1qS5AEqEOwAovkXhTTjnB/y5Mnoha1Pm5tC/15MOSjwclYHEegDBRosbBewOg6Or2ieeRbE1jYW4Sp8HWxhLAybQauqgKqCty8E78ZjG5cPdR54QmDQsypV918cBnKLWabV6UlZ67AprBmSeUo2QUmhOnPLVW4IsmpJuzuiJR9fBuXREk52zcRiXZoIrZqGzknR6xv5AnED2eIKjwciZL34cyOvVTNoX7vL1dM4qfsXzFGFWnX root@3f6b799bd119"
            }
        }
    ]
}

```

```
docker run -v /home/abrenzikofer/gantree-work/:/gantree --env-file envfile.encointer --user $(id -u):$(id -g) --rm -ti gantree-cli-docker sync

Identity added: /gantree/ssh/ssh_id_rsa_validator (/gantree/ssh/ssh_id_rsa_validator)
Error loading key "/gantree/ssh/ssh_id_rsa_validator.pem": invalid format
Error loading key "/gantree/ssh/ssh_id_rsa_validator.pub": invalid format



 ██████╗  █████╗ ███╗   ██╗████████╗██████╗ ███████╗███████╗
██╔════╝ ██╔══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔════╝██╔════╝
██║  ███╗███████║██╔██╗ ██║   ██║   ██████╔╝█████╗  █████╗
██║   ██║██╔══██║██║╚██╗██║   ██║   ██╔══██╗██╔══╝  ██╔══╝
╚██████╔╝██║  ██║██║ ╚████║   ██║   ██║  ██║███████╗███████╗
 ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝

[!] Using override for Gantree config path

[!] Using override for inventory path

2020-04-02T12:53:47.635Z [Gantree] (lib/gantree) info: reading gantree configuration
2020-04-02T12:53:47.662Z [Gantree] (lib/config/validate) info: Gantree configuration validated successfully
2020-04-02T12:53:47.663Z [Gantree] (lib/config/preprocessors/boolToString) info: converting booleans in config to strings
2020-04-02T12:53:47.663Z [Gantree] (lib/config/preprocessors/injectEnvVars) info: injecting environment variables into config
2020-04-02T12:53:47.664Z [Gantree] (lib/config/inject) info: injecting defaults
2020-04-02T12:53:47.664Z [Gantree] (lib/ansible/inventory) info: creating namespace
2020-04-02T12:53:47.664Z [Gantree] (lib/ansible/inventory) info: namespace created
2020-04-02T12:53:47.665Z [Gantree] (lib/ansible/inventory) info: creating Gantree inventory
2020-04-02T12:53:47.709Z [Gantree] (lib/ansible/inventory) warn: Gantree config hash has changed since creation
expected: 2e57e06b4f6dbe9f1818985e485c16e5514327682ca42da2a073514d4906408b
     got: 7d498a53ed95c3cd58a2105d591fec475170053f15b43987b59a8cb9013fb926
2020-04-02T12:53:47.709Z [Gantree] (lib/ansible/inventory) info: Gantree inventory created
2020-04-02T12:53:47.710Z [Gantree] (lib/ansible/commands) info: running playbook: /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml
2020-04-02T12:53:47.710Z [Gantree] (cmd) info: Executing: ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml, {"verbose":true}
2020-04-02T12:53:48.234Z [Gantree] (cmd) error: Error occured during command execution 'ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml':
Unhandled error:
 Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
    os.makedirs(b_rpath, mode)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/.ansible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 554, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 498, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 121, in ensure_type
    makedirs_safe(value, 0o700)
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'



2020-04-02T12:53:48.234Z [Gantree] (cmd) error: Error occured during command execution 'ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml':
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
    os.makedirs(b_rpath, mode)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/.ansible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 554, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 498, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 121, in ensure_type
    makedirs_safe(value, 0o700)
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 62, in <module>
    import ansible.constants as C
  File "/usr/lib/python3.8/site-packages/ansible/constants.py", line 174, in <module>
    config = ConfigManager()
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 290, in __init__
    self.update_config_data()
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 566, in update_config_data
    raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e)
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'


2020-04-02T12:53:48.241Z [Gantree] (cmd) error: Execution failed with code 1: ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml
(node:17) UnhandledPromiseRejectionWarning: Error: 1
    at childCloseCallback (/usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/src/lib/cmd.js:117:18)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/src/lib/cmd.js:55:5)
    at ChildProcess.emit (events.js:323:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by DrTexx** [comment]
Hi @brenzi, we're having a look into this now.

The most recent documentation re. configurations can be found in the gantree-lib repository [here](https://github.com/flex-dapps/gantree-lib-nodejs#gantree-configuration), it's accurate to gantree-cli v0.8.0 and gantree-lib v0.6.0.

As a sidenote, configurations no longer require a public key as this is now extracted from the pem private key.

**Comment by DrTexx** [comment]
@brenzi Could you please let us know your:
- OS and version
- Output from `id -u`
- Output from `id -g`
- Your docker version

**Comment by brenzi** [comment]
* ubuntu 18.04
* id -u ->1004
* id -g -> 1004
* Docker version 18.09.7, build 2d0083d

**Comment by DrTexx** [comment]
Thanks for that :+1:
I'll try reproducing the error.

**Comment by DrTexx** [comment]
@brenzi I haven't had any luck reproducing this error.

Would you mind trying the same configuration with the latest release of the dockerized cli to see if this issue is persistent?

**Comment by brenzi** [comment]
Just tried, but I think your documentation is just not ready (and the abovementioned error is still there):

I followed the instructions [here](https://github.com/flex-dapps/gantree-cli-docker/blob/master/README.md)
 So I did
```
git clone https://github.com/flex-dapps/gantree-cli-docker.git
cd gantree-cli-docker
docker build -t gantree-cli-docker .
mkdir ~/gantree-work/
cd gantree-work
mkdir config
mkdir ssh
nano config/encointer-testnet.json
cd ssh
ssh-keygen -f ./my_validator_key -t rsa -m PEM -q -N ""
mkdir ~/gantree-env
nano ~gantree-env/envfile.encointer

docker run -v ~/gantree-work/:/gantree --env-file ~/gantree-env/envfile.encointer --user $(id -u):$(id -g) --rm -ti gantree-cli-docker sync
```

But then I get
```
FAIL:[8] bad config: ENOENT: no such file or directory, open '/gantree/ssh/ssh_id_rsa_validator'
```
So your keygen instructions should actually read
```
ssh-keygen -f ./ssh_id_rsa_validator -t rsa -m PEM -q -N ""
```
but then I launch it again and get:
```
docker run -v ~/gantree-work/:/gantree --env-file ~/gantree-env/envfile.encointer --user $(id -u):$(id -g) --rm -ti gantree-cli-docker sync

Identity added: /gantree/ssh/ssh_id_rsa_validator (/gantree/ssh/ssh_id_rsa_validator)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/gantree/ssh/ssh_id_rsa_validator.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.



 ██████╗  █████╗ ███╗   ██╗████████╗██████╗ ███████╗███████╗
██╔════╝ ██╔══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔════╝██╔════╝
██║  ███╗███████║██╔██╗ ██║   ██║   ██████╔╝█████╗  █████╗  
██║   ██║██╔══██║██║╚██╗██║   ██║   ██╔══██╗██╔══╝  ██╔══╝  
╚██████╔╝██║  ██║██║ ╚████║   ██║   ██║  ██║███████╗███████╗
 ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝

[!] Using override for Gantree config path

[!] Using override for inventory path

2020-04-21T07:05:17.428Z [Gantree] (lib/gantree) info: reading gantree configuration
2020-04-21T07:05:17.455Z [Gantree] (lib/config/validate) info: Gantree configuration validated successfully
2020-04-21T07:05:17.456Z [Gantree] (lib/config/preprocessors/boolToString) info: converting booleans in config to strings
2020-04-21T07:05:17.456Z [Gantree] (lib/config/preprocessors/injectEnvVars) info: injecting environment variables into config
2020-04-21T07:05:17.457Z [Gantree] (lib/config/inject) info: injecting defaults
2020-04-21T07:05:17.457Z [Gantree] (lib/ansible/inventory) info: creating namespace
2020-04-21T07:05:17.457Z [Gantree] (lib/ansible/inventory) info: namespace created
2020-04-21T07:05:17.458Z [Gantree] (lib/ansible/inventory) info: creating Gantree inventory
2020-04-21T07:05:17.505Z [Gantree] (lib/ansible/inventory) info: Gantree config hash written (7d498a53ed95c3cd58a2105d591fec475170053f15b43987b59a8cb9013fb926)
2020-04-21T07:05:17.505Z [Gantree] (lib/ansible/inventory) info: Gantree inventory created
2020-04-21T07:05:17.505Z [Gantree] (lib/ansible/commands) info: running playbook: /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml
2020-04-21T07:05:17.506Z [Gantree] (cmd) info: Executing: ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml, {"verbose":true}
2020-04-21T07:05:18.057Z [Gantree] (cmd) error: Error occured during command execution 'ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml': 
Unhandled error:
 Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
    os.makedirs(b_rpath, mode)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/.ansible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 554, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 498, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 121, in ensure_type
    makedirs_safe(value, 0o700)
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'



2020-04-21T07:05:18.066Z [Gantree] (cmd) error: Error occured during command execution 'ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml': 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 85, in makedirs_safe
    os.makedirs(b_rpath, mode)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/.ansible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 554, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 498, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 121, in ensure_type
    makedirs_safe(value, 0o700)
  File "/usr/lib/python3.8/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
ansible.errors.AnsibleError: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 62, in <module>
    import ansible.constants as C
  File "/usr/lib/python3.8/site-packages/ansible/constants.py", line 174, in <module>
    config = ConfigManager()
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 290, in __init__
    self.update_config_data()
  File "/usr/lib/python3.8/site-packages/ansible/config/manager.py", line 566, in update_config_data
    raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e)
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'


2020-04-21T07:05:18.073Z [Gantree] (cmd) error: Execution failed with code 1: ansible-playbook -i /gantree/inventory/nctr-test/gantree -i /gantree/inventory/nctr-test/active /usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/ansible/infra.yml
(node:17) UnhandledPromiseRejectionWarning: Error: 1
    at childCloseCallback (/usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/src/lib/cmd.js:117:18)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/gantree-cli/node_modules/gantree-lib/src/lib/cmd.js:55:5)
    at ChildProcess.emit (events.js:323:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```
